### ISSUE TITLE
Make the function timeCalc return an array 

### ISSUE THREAD

**Issue by SteveSayantan** [Susmita-Dey/all-round-calculator#14]
[https://github.com/Susmita-Dey/all-round-calculator/blob/main/package/index.js](Link to the file) ### Line number 181

 if the timeCalc function is set to return an array instead of a string, the user can implement the data in the code as per requirement, which in case of an hard-coded string makes it difficult.

**Comment by Susmita-Dey** [comment]
> [https://github.com/Susmita-Dey/all-round-calculator/blob/main/package/index.js](Link to the file) ### Line number 181
> 
> if the timeCalc function is set to return an array instead of a string, the user can implement the data in the code as per requirement, which in case of an hard-coded string makes it difficult.

Can you elaborate more like what you wanna change and what would be the outcome?
_P.S. Screenshots are welcome._

**Comment by SteveSayantan** [comment]
> > [https://github.com/Susmita-Dey/all-round-calculator/blob/main/package/index.js](Link to the file) ### Line number 181
> > if the timeCalc function is set to return an array instead of a string, the user can implement the data in the code as per requirement, which in case of an hard-coded string makes it difficult.
> 
> Can you elaborate more like what you wanna change and what would be the outcome? _P.S. Screenshots are welcome._

[https://gist.github.com/SteveSayantan/85773e3a0f6b1f1f34553a341a87175c](url) 
This function returns an array containing all the data which may help making this reusable.

**Comment by Susmita-Dey** [comment]
> Check [this](https://gist.github.com/SteveSayantan/85773e3a0f6b1f1f34553a341a87175c) out This function returns an array containing all the data which may help making this reusable i.e. user can use it multiple times as per requirement.

Yes, I get it. But you need to make more improvements in your code.
