### ISSUE TITLE
"Scientific Calculator"?

### ISSUE THREAD

**Issue by Shivam-Katare** [Susmita-Dey/all-round-calculator#19]
Hey, I have one question, can we also add a **Scientific Calculator** to this? A scientific Calculator makes this project more efficient.

**Comment by Susmita-Dey** [comment]
> Hey, I have one question, can we also add a **Scientific Calculator** to this? A scientific Calculator makes this project more efficient.

Sure. Do you wanna take up this issue?

**Comment by Shivam-Katare** [comment]
Yes, I can try it once.
