### ISSUE TITLE
Use real-time values for currencies conversion

### ISSUE THREAD

**Issue by Jighdan** [Susmita-Dey/all-round-calculator#22]
Instead of hard-coding the values for each currency.

**Comment by Susmita-Dey** [comment]
> Instead of hard-coding the values for each currency.

Do you want to work on this issue?

**Comment by Jighdan** [comment]
This one shouldn't be difficult either, involves research and dealing with the API limitations, again, if no one takes this in a week, I'll work on it

**Comment by Susmita-Dey** [comment]
@Jighdan Go ahead. 🚀

**Comment by EshaanAgg** [comment]
@Susmita-Dey 
I would like to work on this issue if no one else is currently working on it.

**Comment by Susmita-Dey** [comment]
@EshaanAgg Go ahead

**Comment by EshaanAgg** [comment]
@Susmita-Dey 
Wanted to inform you about a couple of changes that this feature would need.
- I would need to add "Axios" as a new dependency for the npm package as I would be using it to fetch live currency values from a free API.
- Also now the `getCurrency()` function would now be an asynchronous function and thus would need to be called a bit differently. I'll update the same in the documentation as well. 

Should I proceed implementing these?

**Comment by Susmita-Dey** [comment]
@EshaanAgg Yes do it but kindly note that the docs website is made with `docsify` so you have to update the markdown files in order to update the docs website
