### ISSUE TITLE
Separate the functions in index.js to their own modules

### ISSUE THREAD

**Issue by Jighdan** [Susmita-Dey/all-round-calculator#23]
So that the code is cleaner and structured

**Comment by Susmita-Dey** [comment]
> So that the code is cleaner and structured

Do you want to work on this issue?

**Comment by Jighdan** [comment]
Sure, but I think this would be an issue best suited for a less experienced dev. If anyone doesn't take this by next week, pin me and I'll happily send an MR :-)

**Comment by Susmita-Dey** [comment]
> Sure, but I think this would be an issue best suited for a less experienced dev. If anyone doesn't take this by next week, pin me and I'll happily send an MR :-)

Okay.

**Comment by Roshani9731** [comment]
@Susmita-Dey  Can I work on this issue?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Can I work on this issue?

Yes, go ahead.

**Comment by bhattabhi013** [comment]
Is it still open?

**Comment by Susmita-Dey** [comment]
@bhattabhi013 Yes. Assigning this to you as @Roshani9731 haven't made any PR till now.

**Comment by AwsYaseen22** [comment]
Hi there, is it still open?!

**Comment by bhattabhi013** [comment]
Hi @AwsYaseen22,
I'm working on it. 
Thanks
