### ISSUE TITLE
Use the Rest Parameter with functions doAddN() and doMultN()

### ISSUE THREAD

**Issue by swapn652** [Susmita-Dey/all-round-calculator#28]
### Describe your Issue

I think it would be better if we pass the rest parameter with these two functions, rather than the array. 
Then we can do this:

    console.log(calculator.doAddN(5,7,12,13));

rather than this:
   
    console.log(calculator.doAddN([5,7,12,13]));

This would seem more logical as we are multiplying or adding multiple individual numbers, rather than the content of an array.

**Comment by Susmita-Dey** [comment]
Yes, I agree with you. 
@swapn652 Do you want to work on this issue?

**Comment by swapn652** [comment]
Yes, sure. Assign me I will do it.

**Comment by Susmita-Dey** [comment]
> Yes, sure. Assign me I will do it.

Go ahead 🚀🚀
