### ISSUE TITLE
Create issue and PR templates

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/all-round-calculator#3]
I need the templates for creating issues and PR.

**Comment by vedantpople4** [comment]
Checkout these links for
1. Issue Template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
2. PR Template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Susmita-Dey** [comment]
Closing this issue as completed by #24
