### ISSUE TITLE
dynamic value for doInc() and doDecr()

### ISSUE THREAD

**Issue by rahmat-st** [Susmita-Dey/all-round-calculator#33]
### Name

Rahmat Sulistio

### Describe your Issue

The doInc() and doDecr() functions must have dynamic value to increment/decrement. For example, if we want to increment/decrement with 3, we do not have to call the function 3 times, just pass the value. But the function still has the default value of 1.

Do you need it? Can I work for it?

**Comment by rahmat-st** [comment]
Hi @Susmita-Dey, can you assign me?

**Comment by Susmita-Dey** [comment]
@rahmat-st Go ahead
