### ISSUE TITLE
Add functionality to calculate power of a number

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/all-round-calculator#50]
### Name

Abhishek

### Describe your Issue

Add new functionality to calculate the power of a number.

**Comment by ays14** [comment]
I can take this up

**Comment by ays14** [comment]
@bhattabhi013 @Susmita-Dey please review PR #52

**Comment by bhattabhi013** [comment]
hi @ays14,
Thanks for joining the community. I'm just a fellow contributor to this project.
As I can see you've already created a PR, so you can take up this issue, however, next time please get the issue assigned to yourself before working on it.

**Comment by ays14** [comment]
> hi @ays14, Thanks for joining the community. I'm just a fellow contributor to this project. As I can see you've already created a PR, so you can take up this issue, however, next time please get the issue assigned to yourself before working on it.

Hi @bhattabhi013 , as you mentioned, I thought you're a maintainer and hence went ahead with the PR. Will take care next time onwards. Thanks.
