### ISSUE TITLE
Generate random number

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/all-round-calculator#51]
### Name

Abhishek

### Describe your Issue

Add functionality to generate a random number.

**Comment by sumit-022** [comment]
Do we have to program this? Like in C++ or Java sort of?

**Comment by Susmita-Dey** [comment]
@bhattabhi013 I guess it's there in the package. Kindly check once

**Comment by bhattabhi013** [comment]
It's not there, I've searched for the keyword 'rand' and 'random' but found no results in the package.

**Comment by ays14** [comment]
@bhattabhi013 if you don't mind, would you like to delegate this to me?
