### ISSUE TITLE
Function Documentation

### ISSUE THREAD

**Issue by Dun-sin** [Susmita-Dey/all-round-calculator#6]
Writing docs for functions so users can use it properly

**Comment by Susmita-Dey** [comment]
> Writing docs for functions so users can use it properly

The thing which you have done is okay. I want to document it like proper documentation as MDN Docs have inside my docs folder.

**Comment by Dun-sin** [comment]
you could convert comments to docs I think

**Comment by Susmita-Dey** [comment]
> you could convert comments to docs I think

How? Manually or do you know any tools?

**Comment by Dun-sin** [comment]
> > you could convert comments to docs I think
> 
> How? Manually or do you know any tools?

There's a tool that looks at your code then converts every comment into a doc

**Comment by Susmita-Dey** [comment]
> There's a tool that looks at your code then converts every comment into a doc

Can you name it?

**Comment by Dun-sin** [comment]
> Can you name it?

JsDocs

**Comment by hacknorris-aka-penguin** [comment]
i pr'ed smth realted tbh... but its only a markdown file... o.O

**Comment by Susmita-Dey** [comment]
> JsDocs

Okay.
